config/routes.rb
Rails.application.routes.draw do
  resources :names

  resources :comments

  resources :posts

  resources :events

  resources :joins
  root to: redirect('/top/index')
  
  get 'top/index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :names
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'イベント登録が完了しました！' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: '以下の通りにイベントが変更されました！' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
      @names = @event.names.all
      @name = @event.names.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :eventsName, :freeSpace)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :eventsName %><br>
    <%= f.text_field :eventsName %>
  </div>
  <div class="field">
    <%= f.label :freeSpace %><br>
    <%= f.text_area :freeSpace %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>イベントの変更</h1>

  <%= render 'form' %>

<br><br>
<a href="/">TOPに戻る</a>

app/views/events/index.html.erb
<h1>イベント一覧</h1>
<br><br>

<TABLE border="1" align="left">
<TR>
<TD>日時</TD>
<TD>イベント名</TD>
<TD>その他の事項</TD>
</TR>
<tbody>
  <% @events.each do |event| %>
<TR>
<TD><%= event.date %></TD>
<TD><%= event.eventsName %></TD>
<TD><%= event.freeSpace %></TD>
 <TD><BUTTON type="submit"><%= link_to '詳細', event %></BUTTON></TD>
<TD><BUTTON type="submit"><%= link_to '変更', edit_event_path(event) %></BUTTON></TD>
<TD><BUTTON type="submit"><%= link_to '削除', event, method: :delete, data: { confirm: 'このイベントを削除してもよろしいですか?' } %></BUTTON></TD>
</TR>
  <% end %>
</tbody>
</TABLE>
<br clear="all">

<br><br>


<button type="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-star"></span> <%= link_to '参加する', new_name_path %></button>

<BR><BR>

<a href="/">TOPに戻る</a>

app/views/events/new.html.erb
<h1>イベント登録</h1>

<%= render 'form' %>

<br><br>
<a href="/">TOPに戻る</a>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>日時:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>イベント名:</strong>
  <%= @event.eventsName %>
</p>

<p>
  <strong>自由記入欄:</strong>
  <%= @event.freeSpace %>
</p>

<h3>参加者リスト</h3>
<% @names.each do |name| %>
  <div>
    <p><strong><%= name.name %></strong>
      (<%= name.belong %>)<br />
      <%= link_to 'Delete', name_path(name), method: :delete, data: { confirm: '削除してもよろしいですか？' } %></p>
  </div>
<% end %>

<br><br>

<br><br>
<a href="/">TOPに戻る</a>