config/routes.rb
Rails.application.routes.draw do
  resources :names

  resources :comments

  resources :posts

  resources :events

  resources :joins
  root to: redirect('/top/index')
  
  get 'top/index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end
  


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json.
  def create
   @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        
      	# deliverメソッドを使って、メールを送信する
      	PostMailer.post_email(@post).deliver

        format.html { redirect_to @post, notice: '以下の方に、イベント情報を送信しました！' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @comments = @post.comments.all
      @comment = @post.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:to, :me, :date, :eventName, :freeSpace)
    end
  

  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_area :to %>
  </div>
  <div class="field">
    <%= f.label :me %><br>
    <%= f.text_field :me %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :eventName %><br>
    <%= f.text_field :eventName %>
  </div>
  <div class="field">
    <%= f.label :freeSpace %><br>
    <%= f.text_area :freeSpace %>
  </div>
 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/details.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @post.to %>
</p>

<p>
  <strong>Me:</strong>
  <%= @post.me %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>eventName:</strong>
  <%= @post.eventName %>
</p>

<p>
  <strong>free:</strong>
  <%= @post.freeSpace %>
</p>

<br><br>
<p>続けてイベント告知を行う場合は、</p><BUTTON type="submit"><%= link_to 'こちらをClick', new_post_path %></BUTTON>
<br><br><br>
<a href="/">TOPに戻る</a>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>日時</th>
      <th>イベント名</th>
      <th>自由記入欄</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.date %></td>
        <td><%= post.eventName %></td>
        <td><%= post.freeSpace %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>関係者イベント告知</h1>

<%= render 'form' %>

<br><br>
<a href="/">TOPに戻る</a>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>eventName:</strong>
  <%= @post.eventName %>
</p>

<p>
  <strong>free:</strong>
  <%= @post.freeSpace %>
</p>
<br /><br />

<h3>参加者リスト</h3>
<% @comments.each do |comment| %>
  <div>
    <p><strong><%= comment.user_name %></strong>
    (<%= comment.body %>)<br />
      <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: '削除してもよろしいですか？' } %></p>
  </div>
<% end %>
<br / ><br />
<%= render 'comments/form' %>

<br><br>

<a href="/">TOPに戻る</a>